version: '3.7'

services:
  minerva-db:
    container_name: minerva_db
    image: kadriand/minerva-db-ansep:recon
    environment:
      - POSTGRES_USER=minervauser
      - POSTGRES_PASSWORD=minervapass
      - POSTGRES_DB=minervadb
      - PGDATA=/var/lib/postgresql-static/data
    expose:
      - 5433
    ports:
      - "5433:5433"
    logging:
      options:
        max-size: 50m
  minerva:
    container_name: minerva_app
    image: kadriand/minerva-ansep:recon
    command: >
      bash -c 'sed -i 's/localhost:5433/10.212.12.32:5433/g' /etc/minerva/db.properties
      && while !</dev/tcp/localhost/5433; do echo [`date +%F%t%T%t%Z`] Making db health check; sleep 1; done
      && catalina.sh run'
    environment:
      - JAVA_OPTS=-Djava.awt.headless=true -Xmx3096m -XX:+UseConcMarkSweepGC
    ports:
      - ${MINERVA_PORT:-8080}:8080
    depends_on:
      - minerva-db
    logging:
      options:
        max-size: 50m